### ISSUE TITLE
fix: uncaughtException needs more best practices

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia-http-gateway#112]
```[tasklist]
### Tasks
- [ ] default `ALLOW_UNHANDLED_ERROR_RECOVERY` to false
- [ ] Add warning in readme
- [ ] Add default known-recoverable uncaughtExceptions
- [ ] Add listener to req & resp for ERR_STREAM_PREMATURE_CLOSE
```

https://github.com/ipfs/helia-http-gateway/blob/6f10038693de6001d332d2e92ff666f8f20b9c1c/src/index.ts#L273-L280

related:

- https://github.com/ipfs/helia-http-gateway/issues/18
- https://github.com/ipfs/helia-http-gateway/pull/102#discussion_r1551998955

cc @achingbrain

**Comment by achingbrain** [comment]
> Add default known-recoverable uncaughtExceptions

There are no recoverable uncaught exceptions.  This is clearly documented.

> The event should not be used as an equivalent to On Error Resume Next. Unhandled exceptions inherently mean that an application is in an undefined state. Attempting to resume application code without properly recovering from the exception can cause additional unforeseen and unpredictable issues.
>
> The correct use of 'uncaughtException' is to perform synchronous cleanup of allocated resources (e.g. file descriptors, handles, etc) before shutting down the process. It is not safe to resume normal operation after 'uncaughtException'.
>
> https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly

Note:

> It is not safe to resume normal operation after 'uncaughtException'.

**Comment by achingbrain** [comment]
Fixed by #154
